### PR TITLE
EZP-25653: Allow use of eZSupportTools in PlatformUI

### PR DESCRIPTION
**Pull request by glye**
> Part of https://jira.ez.no/browse/EZP-25653
> Status: Ready for review

Removed default_settings.yml as it conflicts with the same in platformui (it resets the collectors).
Ref https://github.com/ezsystems/PlatformUIBundle/pull/542

### CODE REVIEW

**Comment by bdunogier** [comment]
The title can't be right: ez-support-tools doesn't know about PlatformUI ;-)

Jokes aside, on its own, ezsystems/ez-support-tools will break with this patch: it will try to use `$system_info_view$` as a service argument. We can't rely on platform-ui-bundle declaring it.

But it is true that this will break platform-ui. I see three ways around this:
1. load the support tools bundle *before* PlatformUI, so that the latter overrides the empty setting
2. add a compiler pass to support tools that declares this setting if it has not been declared
3. implement semantic config (I have a skeleton for this)

The commit must be changed to say what it does (`Removed default_settings.yml`). So would the PR, but it's not as important if it ends up containing more commits.

In any case, I can't be +1 as it is (break).

**Comment by glye** [comment]
Thanks for the help. 1 or 2 seem the faster ways to get to a usable solution.

> The title can't be right: ez-support-tools doesn't know about PlatformUI ;-) Jokes aside(...)

I don't get the joke, the title isn't assuming ez-support-tools knows about platformui...?

**Comment by bdunogier** [comment]
Damn, probably french / my type of humour :-)

Anyway, the end of my comment should explain what I mean in reality.

**Comment by bdunogier** [comment]
Solution is probably the easiest, since you will have to create an ezplatform PR (see platformUI comment). You can set the order here, and it should work as expected.

**Comment by andrerom** [comment]
Title fixed.

**Comment by glye** [comment]
Closing, not needed.

**Pull request closed without merging**
