### PR TITLE
[WIP] Fix EZP-25536: eZSupportTools review

### PR DESCRIPTION
**Pull request by glye**
> Fixes https://jira.ez.no/browse/EZP-25536
> Status: Work in progress

The ez-support-tools repo was created without peer review, this aims to fix that. There are three existing commits in master, of these only the first is really interesting, the others are trivial.
1. https://github.com/ezsystems/ez-support-tools/commit/116a6d7290a316183e672762944d7c41cf84cd5c
2. https://github.com/ezsystems/ez-support-tools/commit/0e0ea114cf3d6607525eb9339b20627e477b4e90
3. https://github.com/ezsystems/ez-support-tools/commit/cf61fe9a2fe40ac9d6d3150ac225e6b39806d691

My TODO:
- [ ] Find a better way to inject the InfoProviders? (using a variadic constructor at the moment, not sure if legit)
- [ ] Get the platformui integration working, so existing sysinfo code in platformui can be removed/deprecated
- [x] ~~Command, see https://github.com/ezsystems/ez-support-tools/pull/1~~
- [ ] Tests

Feedback from @dpobel:
- [x] D1) Let InfoProvider return a ValueObject instead of array https://github.com/ezsystems/ez-support-tools/commit/116a6d7290a316183e672762944d7c41cf84cd5c#commitcomment-16469472
- [ ] D2) Separate template from InfoProvider https://github.com/ezsystems/ez-support-tools/commit/116a6d7290a316183e672762944d7c41cf84cd5c#commitcomment-16468867
- [x] D3) Add `ezcSystemInfo` dependency to composer.json https://github.com/ezsystems/ez-support-tools/commit/116a6d7290a316183e672762944d7c41cf84cd5c#commitcomment-16468900
- [x] D4) Change YUI prefix `ezconf` to `ezst` https://github.com/ezsystems/ez-support-tools/commit/116a6d7290a316183e672762944d7c41cf84cd5c#commitcomment-16469054

Feedback from @bdunogier:
- [ ] B1) Make routing paths less generic. (Maybe: `ezst/sysinfo/*`?) https://github.com/ezsystems/ez-support-tools/commit/116a6d7290a316183e672762944d7c41cf84cd5c#commitcomment-16494288

### CODE REVIEW

**Comment by glye** [comment]
Early review ping @dpobel @andrerom @bdunogier @yannickroger - this is mainly about the architecture. See first commit: https://github.com/ezsystems/ez-support-tools/commit/116a6d7290a316183e672762944d7c41cf84cd5c

D1 and D2 are debatable. For D1 I'm unsure about the advantages. D2 seems a good thing - do we have an existing parallell I can base it on?
Any other architectural concerns?

**Comment by bdunogier** [comment]
I'm lost. You speak about multiple changes, but there's only one commit... please help : -)

**Comment by glye** [comment]
@bdunogier D3 and D4 are trivial, so I committed them together. I have amended the commit to make that clear, and I'll keep the others in separate, described commits.

**Comment by bdunogier** [comment]
> For D1 I'm unsure about the advantages.

Value objects are important in domain driven architectures. Which we more or less follow.
It provides readability, eases, BC, and it is overall more consistent with the rest of the system.

Connected to D2, I'm thinking that once we have value objects, we could dig a bit southward, and consider re-using the view system, already used by ContentView, and planned for usage by ContentEdit (part of https://github.com/ezsystems/repository-forms/pull/62).

It would cover the template + rendering parts, and would let you focus on the system info one. It would also implicitly give us easy ways to (let) override view templates & controllers for customization.

**Comment by glye** [comment]
>  I'm otoh not 100% sure if I'd use the same generic object, or a custom one per info. Both choices have consequences.

Do tell, @bdunogier :)

**Comment by bdunogier** [comment]
> Do tell, @bdunogier :)

Custom properties/methods dictate the contract (interface), and make it easier to maintain, document and use.

Generic properties (hash) is more flexible, but only requires one value object.

I'd say it depends on semantic the sysinfos are meant/supposed to be (now, and in the future). Should we want to do anything special with any of them, then I'd go for more semantic => one ValueObject per Info item.

**Comment by glye** [comment]
@bdunogier As far as has been discussed, no special actions have been mentioned. They need different templates for browser rendering, but that's would be handled by Views and is not relevant here, right? So that would indicate single value object.

Otoh a generic value object would just be a wrapper for the array that each info provider returns now, right? While a specific one for each could have a property for each of the current array keys. So if readability/documentation is a goal, that would indicate specific values...?

**Comment by glye** [comment]
Added per-provider value objects (the controller isn't updated yet).

**Comment by bdunogier** [comment]
Could you please not amend / rebase during review ? Having new commits for review changes makes it easier to check what has changed.

**Comment by glye** [comment]
@bdunogier 
> Could you please not amend / rebase during review?
Noted. In this case I only changed the commit message to make it clear what it contained.

> Do you need one, given that it does nothing?
Not now, maybe later, and then it might be good for BC to have it in place. If you want it gone, say the word.

**Comment by glye** [comment]
@bdunogier @dpobel Any comment on how best to inject the (variable number of) infoproviders into the controller? The current variadic isn't legit, is it? :)
https://github.com/ezsystems/ez-support-tools/blob/master/Controller/SystemInfoController.php#L22
https://github.com/ezsystems/ez-support-tools/blob/master/Resources/config/services.yml#L29

**Comment by glye** [comment]
@bdunogier 
> Connected to D2, I'm thinking that once we have value objects, we could dig a bit southward, and consider re-using the view system, already used by ContentView

So... make a view that uses `eZ\Publish\Core\MVC\Symfony\View\BaseView` then, in a similar way to ContentView?

**Pull request closed without merging**
